GET https://dapi.kakao.com/v2/local/search/keyword.json?query=삼성&page=20

### 방 생성
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{
  "longitude" : "37.230840",
  "latitude" : "127.190607"
}

### 방 정보 조회
GET http://localhost:8080/api/v1/1

### 방 Resuggest
POST http://localhost:8080/api/v1/resuggest/1

### 음식점 Resuggest
POST http://localhost:8080/api/v1/1/resuggest/11

### 음식점 투표
POST http://localhost:8080/api/v1/1/vote
Content-Type: application/json

{
  "restaurantIdList" : [14]
}

### 최고 음식점 선정
GET http://localhost:8080/api/v1/1/result

### 카카오 API 변환
GET http://localhost:8080/api/v1/info/1
