GET https://dapi.kakao.com/v2/local/search/keyword.json?query=삼성&page=1
Authorization: KakaoAK 8d70680194cad5df035d3b0c209b3e55


###
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{
  "longitude" : "37.230840",
  "latitude" : "127.190607"
}
